site_name: My Docs2

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - search.highlight
    #- toc.integrate
    - toc.follow  
